---
Resources:
  MediaLiveInput:
    Type: AWS::MediaLive::Input
    Properties:
      Name: foobar
      RoleArn: arn:aws:iam::123456789012:role/MediaLive-Input-foobar
      Sources:
        - PasswordParam: b@dP@$sW0rD
          Username: admin
